Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "cicd-server" do |cicd|
    cicd.vm.hostname = "cicd-server"
    cicd.vm.network "private_network", ip: "192.168.56.20"
    cicd.vm.provision :shell, privileged: true, inline: $install_common_tools
  end


end

$install_common_tools = <<-SHELL

# ssh password 접속 활성화
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config;
systemctl restart sshd.service

# 방화벽 해제
systemctl stop firewalld && systemctl disable firewalld
systemctl stop NetworkManager && systemctl disable NetworkManager

# Centos Update
yum -y update
yum -y install wget

# 도커 설치
yum install -y yum-utils device-mapper-persistent-data lvm2 
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce-3:20.10.8-3.el7.x86_64
systemctl daemon-reload
systemctl enable --now docker

# Kubectl 설치
curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Kubectl 자동완성 기능 설치
yum install bash-completion -y
source <(kubectl completion bash)
echo "source <(kubectl completion bash)" >> ~/.bashrc

# Helm 설치
curl -O https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
tar -zxvf helm-v3.4.2-linux-amd64.tar.gz
mv linux-amd64/helm /usr/local/bin/helm

# Helm 자동완성 기능 설치
source <(helm completion bash)
echo "source <(helm completion bash)" > /etc/bash_completion.d/helm

# Jenkins 설치  
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum upgrade -y 
yum install -y epel-release-7-11 java-11-openjdk-devel-1:11.0.12.0.7-0.el7_9
yum install -y jenkins-2.303.2-1.1
systemctl daemon-reload
systemctl enable jenkins
systemctl start jenkins

# Git 설치
yum install -y git-1.8.3.1-23.el7_8




SHELL